// Renders the diagnostics catalog as the human document docs/diagnostics.md. Generated by
// `deno task tools:generate`; a test fails when the committed file differs.
import {
  type DiagnosticEntry,
  DIAGNOSTICS,
} from "../../shared/authoring/diagnostics.js";

function cell(value: string): string {
  return value.replaceAll("|", "\\|");
}

function row(entry: DiagnosticEntry): string {
  const schema = entry.schema ? "schema and resolver" : "resolver only";
  return `| \`${entry.code}\` | ${entry.severity} | \`${
    entry.path || "(document)"
  }\` | ${schema} | ${cell(entry.meaning)} | ${cell(entry.fix)} |`;
}

export function diagnosticsMarkdown(): string {
  const errors = DIAGNOSTICS.filter((entry) => entry.severity === "error");
  const warnings = DIAGNOSTICS.filter((entry) => entry.severity === "warning");
  const header =
    "| Code | Severity | Path | Caught by | Meaning | Fix |\n| --- | --- | --- | --- | --- | --- |";
  return `# lesson/v1 diagnostics reference

Generated from \`src/shared/authoring/diagnostics.js\` by \`deno task tools:generate\`.
Do not edit by hand. The same catalog is served as JSON at \`/api/v1/diagnostics\`.

Every diagnostic the resolver emits has a stable \`code\`, a JSON Pointer \`path\` into
the submitted document, a \`severity\` and a human \`message\`. Key on the code; the
message text can change. Diagnostics are sorted by path (numeric segments
numerically), then by code.

- An **error** makes the document invalid. The resolution API answers \`422\` and
  no draft is created.
- A **warning** leaves the document valid. The API answers \`200\` and includes it.

\`document.object\`, \`document.nesting\` and \`document.size\` run first and alone.
When one fires it is the only diagnostic returned.

The **Caught by** column says whether the JSON Schema at
\`/api/v1/schemas/lesson/v1\` also rejects a document with this problem. "Resolver
only" rules span items (IDs named elsewhere, word counts, lesson-wide ratios) and
are checked only by the resolver and the downloadable validator. Passing the
schema is necessary, not sufficient.

In paths, \`<i>\` and \`<j>\` stand for array indexes and \`<optionId>\` for an option
ID of the Concept.

## Errors (${errors.length})

${header}
${errors.map(row).join("\n")}

## Warnings (${warnings.length})

${header}
${warnings.map(row).join("\n")}
`;
}
