// The skill's two scripts, as source text. They run under Node 20+ and Deno, import the
// bundled validator (a copy of the shared resolver) and never print the bearer token.
import { CANONICAL_ORIGIN } from "../api-docs/openapi.ts";
import { discoveryLinks } from "../api-docs/capabilities.ts";

export function validateScript(): string {
  return `#!/usr/bin/env node
// Validate a lesson/v1 document with the site's own resolver, bundled beside this file.
// Usage: node validate.mjs lesson.json [--remote]
//   --remote  also POST the document to the site's resolution API and require the same result.
// Exit 0 when the document is valid (warnings allowed), 1 when it is not, 2 on usage errors.
// Generated by deno task plugin:generate. Do not edit; regenerate.
import { readFile } from "node:fs/promises";
import process from "node:process";
import { resolveLesson } from "./lesson-validator.js";

const args = process.argv.slice(2);
const remote = args.includes("--remote");
const file = args.find((arg) => !arg.startsWith("--"));
if (!file) {
  console.error("Usage: validate.mjs lesson.json [--remote]");
  process.exit(2);
}

const catalog = JSON.parse(await readFile(new URL("../references/diagnostics.json", import.meta.url), "utf8"));
const fixes = new Map(catalog.diagnostics.map((entry) => [entry.code, entry.fix]));

let document;
try {
  document = JSON.parse(await readFile(file, "utf8"));
} catch (error) {
  console.error(\`FAIL document.json: \${file} is not readable JSON: \${error.message}\`);
  process.exit(1);
}

const result = await resolveLesson(document);
for (const diagnostic of result.diagnostics) {
  const label = diagnostic.severity === "error" ? "FAIL" : "WARN";
  console.log(\`\${label} \${diagnostic.code} at \${diagnostic.path || "/"}: \${diagnostic.message}\`);
  const fix = fixes.get(diagnostic.code);
  if (fix) console.log(\`     fix: \${fix}\`);
}
const errors = result.diagnostics.filter((diagnostic) => diagnostic.severity === "error").length;
const warnings = result.diagnostics.length - errors;

if (remote) {
  const origin = (process.env.LEARN_BASE_URL || "${CANONICAL_ORIGIN}").replace(/\\/$/, "");
  const response = await fetch(origin + "${discoveryLinks.resolver}", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(document) });
  const served = await response.text();
  const same = served === JSON.stringify(result);
  console.log(\`remote \${response.status} from \${origin}: \${same ? "identical to the local result" : "DIFFERS from the local result; update the plugin"}\`);
  if (!same) process.exit(1);
}

if (result.valid) {
  console.log(\`OK: valid lesson/v1, \${warnings} warning(s), fingerprint \${result.fingerprint}\`);
  process.exit(0);
}
console.log(\`FAILED: \${errors} error(s), \${warnings} warning(s). Fix every FAIL and run again.\`);
process.exit(1);
`;
}

export function submitScript(): string {
  return `#!/usr/bin/env node
// Create a private draft on learn.joshhale.me from a valid lesson/v1 document.
// Usage: node submit.mjs lesson.json [--lesson <lessonId>]
// Reads the bearer token from the LEARN_TOKEN environment variable and the site origin from
// LEARN_BASE_URL (default ${CANONICAL_ORIGIN}). The token is never printed, logged or written.
// Exit 0 on 201, 1 on any failure, 2 on usage errors.
// Generated by deno task plugin:generate. Do not edit; regenerate.
import { readFile } from "node:fs/promises";
import process from "node:process";
import { resolveLesson } from "./lesson-validator.js";

const TOKEN_PATTERN = /learn_pat_[A-Za-z0-9_-]+/g;

/** Every line this script prints passes through here, so a token can never reach the terminal. */
function say(text) {
  console.log(String(text).replace(TOKEN_PATTERN, "learn_pat_[redacted]"));
}

const args = process.argv.slice(2);
const file = args.find((arg) => !arg.startsWith("--"));
const lessonFlag = args.indexOf("--lesson");
const lessonId = lessonFlag === -1 ? null : args[lessonFlag + 1];
if (!file || (lessonFlag !== -1 && !lessonId)) {
  console.error("Usage: submit.mjs lesson.json [--lesson <lessonId>]");
  process.exit(2);
}

const token = process.env.LEARN_TOKEN;
if (!token) {
  console.error("LEARN_TOKEN is not set. Export it in the shell that runs the agent; do not paste it into the chat.");
  process.exit(1);
}
if (args.some((arg) => TOKEN_PATTERN.test(arg))) {
  console.error("Never pass the token on the command line. Set LEARN_TOKEN in the environment instead.");
  process.exit(2);
}

const origin = (process.env.LEARN_BASE_URL || "${CANONICAL_ORIGIN}").replace(/\\/$/, "");
const document = JSON.parse(await readFile(file, "utf8"));
const serialized = JSON.stringify(document);
if (TOKEN_PATTERN.test(serialized)) {
  console.error("The lesson document contains a bearer token. Remove it before submitting.");
  process.exit(1);
}

const local = await resolveLesson(document);
if (!local.valid) {
  say(\`The document is not valid (\${local.diagnostics.length} diagnostic(s)). Run validate.mjs first.\`);
  for (const diagnostic of local.diagnostics) say(\`\${diagnostic.severity === "error" ? "FAIL" : "WARN"} \${diagnostic.code} at \${diagnostic.path || "/"}: \${diagnostic.message}\`);
  process.exit(1);
}

const path = lessonId ? \`${discoveryLinks.lessons}/\${encodeURIComponent(lessonId)}/revisions\` : "${discoveryLinks.lessons}";
const response = await fetch(origin + path, {
  method: "POST",
  headers: { authorization: \`Bearer \${token}\`, "content-type": "application/json" },
  body: serialized,
});
const text = await response.text();
let body = null;
try {
  body = JSON.parse(text);
} catch {
  body = null;
}

if (response.status === 201 && body) {
  say(\`Created draft revision (\${response.status}) on \${origin}\`);
  say(\`  lessonId:    \${body.lessonId}\`);
  say(\`  revisionId:  \${body.revisionId}\`);
  say(\`  status:      \${body.status}\`);
  say(\`  fingerprint: \${body.fingerprint ?? local.fingerprint}\`);
  say(\`  revision:    \${origin}${discoveryLinks.lessons}/\${body.lessonId}/revisions/\${body.revisionId}\`);
  say(\`  learn:       \${origin}/learn/\${body.lessonId}\`);
  say("Submitting the same document again returns the same revision.");
  process.exit(0);
}

say(\`Draft creation failed with \${response.status} from \${origin}\${path}\`);
if (response.status === 401) say("The token is missing, invalid, expired or revoked (401). Check LEARN_TOKEN in the shell; do not print it.");
else if (response.status === 403) say("The token lacks the lessons:write scope (403). Mint one with that scope.");
else if (response.status === 422 && body && Array.isArray(body.diagnostics)) {
  say("The server's resolver rejected the document (422):");
  for (const diagnostic of body.diagnostics) say(\`\${diagnostic.severity === "error" ? "FAIL" : "WARN"} \${diagnostic.code} at \${diagnostic.path || "/"}: \${diagnostic.message}\`);
} else if (body && body.title) say(\`\${body.title}: \${body.detail ?? ""}\`);
else say(text.slice(0, 500));
process.exit(1);
`;
}
